const tools=[
{name:'ChatGPT',cat:'IA',icon:'🤖',desc:'Assistente de IA para ideias, textos, estudos, código e tarefas.',rating:4.9,url:'https://chatgpt.com/'},
{name:'Claude',cat:'IA',icon:'🧠',desc:'IA para análise, escrita, raciocínio e criação de conteúdo.',rating:4.8,url:'https://claude.ai/'},
{name:'Perplexity',cat:'IA',icon:'🔎',desc:'Pesquisa com IA para encontrar respostas e explorar assuntos.',rating:4.8,url:'https://www.perplexity.ai/'},
{name:'Gemini',cat:'IA',icon:'✨',desc:'Assistente de IA para pesquisa, ideias e produtividade.',rating:4.7,url:'https://gemini.google.com/'},
{name:'Notion',cat:'Produtividade',icon:'◼️',desc:'Organize projetos, documentos, tarefas e conhecimento.',rating:4.8,url:'https://www.notion.so/'},
{name:'ClickUp',cat:'Produtividade',icon:'✅',desc:'Gestão de tarefas, equipes e projetos em um só lugar.',rating:4.6,url:'https://clickup.com/'},
{name:'Canva',cat:'Design',icon:'🎨',desc:'Crie posts, apresentações, vídeos, logos e artes.',rating:4.8,url:'https://www.canva.com/'},
{name:'CapCut',cat:'Design',icon:'✂️',desc:'Editor de vídeos para Reels, Shorts e conteúdo rápido.',rating:4.6,url:'https://www.capcut.com/'},
{name:'HubSpot',cat:'Negócios',icon:'🟠',desc:'Ferramentas para marketing, vendas, CRM e relacionamento.',rating:4.6,url:'https://www.hubspot.com/'},
{name:'NordVPN',cat:'Segurança',icon:'🛡️',desc:'Privacidade e segurança para sua navegação.',rating:4.7,url:'https://nordvpn.com/'},
{name:'Jasper',cat:'IA',icon:'🪄',desc:'Criação de conteúdo com inteligência artificial.',rating:4.7,url:'https://www.jasper.ai/'},
{name:'Grammarly',cat:'Produtividade',icon:'✍️',desc:'Ajuda a revisar textos e escrever com mais clareza.',rating:4.6,url:'https://www.grammarly.com/'},
{name:'Adobe Express',cat:'Design',icon:'🖌️',desc:'Criação rápida de peças, vídeos e conteúdo visual.',rating:4.6,url:'https://www.adobe.com/express/'},
{name:'Zapier',cat:'Negócios',icon:'⚡',desc:'Automatize tarefas conectando aplicativos e serviços.',rating:4.7,url:'https://zapier.com/'},
{name:'Bitwarden',cat:'Segurança',icon:'🔐',desc:'Gerenciador de senhas para proteger suas contas.',rating:4.7,url:'https://bitwarden.com/'}
];
let filter='Todos', favs=JSON.parse(localStorage.getItem('fusaFavs')||'[]');
const grid=document.querySelector('#grid'),search=document.querySelector('#search'),sort=document.querySelector('#sort');
function render(){const q=search.value.trim().toLowerCase();let a=tools.filter(x=>(filter==='Todos'||x.cat===filter)&&(x.name.toLowerCase().includes(q)||x.cat.toLowerCase().includes(q)||x.desc.toLowerCase().includes(q)));if(sort.value==='name')a.sort((x,y)=>x.name.localeCompare(y.name));if(sort.value==='rating')a.sort((x,y)=>y.rating-x.rating);grid.innerHTML=a.map(x=>{const saved=favs.includes(x.name);return `<article class="tool"><button class="fav ${saved?'saved':''}" data-f="${x.name}" aria-label="${saved?'Remover':'Adicionar'} ${x.name} aos favoritos">${saved?'★':'☆'}</button><div class="icon">${x.icon}</div><h3>${x.name}</h3><span class="tag">${x.cat}</span><p>${x.desc}</p><div class="rating">★ ${x.rating.toFixed(1)} • recomendado</div><button class="know" data-tool="${x.name}">Conhecer ↗</button></article>`}).join('');document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>fav(b.dataset.f));document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>openTool(b.dataset.tool));document.querySelector('#empty').style.display=a.length?'none':'block';}
function fav(n){favs=favs.includes(n)?favs.filter(x=>x!==n):[...favs,n];localStorage.setItem('fusaFavs',JSON.stringify(favs));document.querySelector('#fav i').textContent=favs.length;render();toast(favs.includes(n)?`${n} foi salvo nos favoritos.`:`${n} saiu dos favoritos.`)}
function openTool(n){const x=tools.find(t=>t.name===n);if(!x)return;document.querySelector('#modalContent').innerHTML=`<div class="modal-meta">${x.cat} • ★ ${x.rating.toFixed(1)}</div><h2>${x.icon} ${x.name}</h2><p>${x.desc}</p><p><strong>Dica:</strong> quando você tiver um link de afiliado, substitua o endereço deste botão pelo seu link personalizado.</p><a class="btn" href="${x.url}" target="_blank" rel="noopener sponsored">Abrir ferramenta ↗</a><button class="btn secondary" onclick="copyLink('${x.url}')">Copiar link</button>`;document.querySelector('#modal').classList.add('open');document.querySelector('#modal').setAttribute('aria-hidden','false')}
function copyLink(url){navigator.clipboard?.writeText(url).then(()=>toast('Link copiado!')).catch(()=>toast(url))}
function closeModal(){document.querySelector('#modal').classList.remove('open');document.querySelector('#modal').setAttribute('aria-hidden','true')}
function toast(s){const t=document.querySelector('#toast');t.textContent=s;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2800)}
document.querySelectorAll('.cats button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.cats button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.cat;document.querySelector('#ferramentas').scrollIntoView({behavior:'smooth',block:'start'});render()});search.oninput=render;sort.onchange=render;document.querySelector('#fav').onclick=()=>toast(favs.length?`Você tem ${favs.length} favorito(s) salvo(s) neste aparelho.`:'Você ainda não tem favoritos.');document.querySelector('#form').onsubmit=e=>{e.preventDefault();toast('E-mail recebido! Para envio real, conecte o formulário ao seu serviço de e-mail.');e.target.reset()};document.querySelector('#menu').onclick=()=>document.querySelector('#links').classList.toggle('open');document.querySelectorAll('#links a').forEach(a=>a.onclick=()=>document.querySelector('#links').classList.remove('open'));document.querySelector('#modalClose').onclick=closeModal;document.querySelector('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});window.addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;document.querySelector('#progress').style.width=h?`${scrollY/h*100}%`:'0%';document.querySelector('#top').style.display=scrollY>450?'block':'none'});document.querySelector('#top').onclick=()=>scrollTo({top:0,behavior:'smooth'});
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.1});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));
document.querySelector('#fav i').textContent=favs.length;render();
